cam_model: Pinhole
cam_width: 1280
cam_height: 720
scale: 1.0
cam_fx: 642.077880859375
cam_fy: 641.0497436523438
cam_cx: 653.4876708984375
cam_cy: 362.3664245605469
cam_d0: -0.05462609976530075   # k1
cam_d1: 0.0651639848947525    # k2
cam_d2: 8.407520908804145e-06    # p1 (8.407...e-06)
cam_d3: 0.0012031124206259847    # p2
